import type { AwayMap, Household, WeekOverrideMap } from '../types'
import {
  buildPrintCalendar,
  DEFAULT_PRINT_WEEKS,
} from '../lib/printCalendar'

export interface PrintCalendarProps {
  household: Household
  away: AwayMap
  overrides?: WeekOverrideMap
  fromWeekKey: string
  weekCount?: number
}

export function PrintCalendar({
  household,
  away,
  overrides = {},
  fromWeekKey,
  weekCount = DEFAULT_PRINT_WEEKS,
}: PrintCalendarProps) {
  const rows = buildPrintCalendar(
    household,
    away,
    fromWeekKey,
    weekCount,
    overrides,
  )
  const people = household.people

  return (
    <section className="print-calendar" aria-label="Printable chore calendar">
      <header className="print-calendar__header">
        <p className="print-calendar__eyebrow">Flat Chores</p>
        <h1>Chore rota</h1>
        <p className="print-calendar__meta">
          {weekCount} weeks from {rows[0]?.label ?? fromWeekKey}
          {people.length > 0 ? ` · ${people.length} people` : null}
        </p>
      </header>

      {people.length === 0 ? (
        <p className="print-calendar__empty">No people in this household yet.</p>
      ) : (
        <table className="print-calendar__table">
          <thead>
            <tr>
              <th scope="col">Week</th>
              {people.map((person) => (
                <th key={person.id} scope="col">
                  {person.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.weekKey}>
                <th scope="row">
                  <span className="print-calendar__week-label">{row.label}</span>
                  <span className="print-calendar__week-key">{row.weekKey}</span>
                </th>
                {people.map((person) => {
                  const cell = row.cells[person.id]
                  if (!cell || cell.status === 'empty') {
                    return (
                      <td key={person.id} className="is-empty">
                        —
                      </td>
                    )
                  }

                  if (cell.status === 'holiday') {
                    return (
                      <td key={person.id} className="is-holiday">
                        {cell.holidayLabel ?? 'Holiday'}
                      </td>
                    )
                  }

                  return (
                    <td key={person.id}>
                      <ul>
                        {cell.choreNames.map((name) => (
                          <li key={name}>{name}</li>
                        ))}
                      </ul>
                    </td>
                  )
                })}
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <footer className="print-calendar__footer">
        Generated by Flat Chores · holidays skip chores when away 4+ days in a
        week
      </footer>
    </section>
  )
}

export default PrintCalendar
